server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

jwt:
  secret: "qwertyuiop7418520"
  expire-time: 1440
  token-prefix: "Bearer "
  header: "token"

spring:
  mvc:
    view:
      static-path-pattern: /**

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  #  data:
  #    mongodb:
  #      uri: mongodb://192.168.154.100:27017/springboot
  #      database: springboot
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/shop?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      enabled: true
      max-request-size: 200MB
      max-file-size: 200MB

  messages:
    cache-duration: 3600
    encoding: UTF-8
    fallback-to-system-locale: true
    basename: i18n/messages
  thymeleaf:
    cache: false

  redis:
    database: 0
    port: 6379
    lettuce:
      pool:
        #最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
    timeout: 5000
    host: 192.168.154.100
logging:
  level:
    root: info
    web: debug
  file:
    name: logs/shop.log

mybatis-plus:
  type-aliases-package: com/euphoria/shop/entity
  mapper-locations: classpath:com/euphoria/shop/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

#
#rocketmq:
#  producer:
#    max-message-size: 4096
#    retry-times-when-send-failed: 2
#    group-name: shop-producer-group
#    namesrv-addr: 192.168.154.100:9876
#    send-msg-time-out: 300000
#  consumer:
#    group-name: shop-consumer-group
#    namesrv-addr: 192.168.154.100:9876
#    topics: order;coupon
#    consume-thread-min: 5
#    consume-thread-max: 32
#    consume-message-batch-max-size: 1






